spring:
  datasource:
    url: jdbc:mysql://mydb:3306/base_activiti?characterEncoding=UTF-8
    username: user
    password: user
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate.ddl-auto: create
    show-sql: true
